
build_browser:
	ionic cordova build browser --prod --release

build_android:
	ionic cordova build android --prod

run_browser:
	ionic serve

run_android:
	rm -rf www/*
	ionic cordova run android --device --livereload -c
